using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Edge_tts_sharp.Model;

/// <summary>
/// Provides a serialization context for lists of eVoice objects, enabling efficient JSON serialization and deserialization using System.Text.Json.
/// </summary>
/// <remarks>This class is generated by a source generator and is intended to optimize serialization performance
/// for collections of eVoice. It should be used when serializing or deserializing lists of eVoice with System.Text.Json
/// to leverage compile-time metadata and reduce runtime overhead.</remarks>
[JsonSerializable(typeof(List<eVoice>))]
public partial class VoiceListJsonContext : JsonSerializerContext
{
}

/// <summary>
/// 语音对象模型，包含语音的各种属性
/// </summary>
public class eVoice
{
    /// <summary>
    /// 语音的完整名称
    /// </summary>
    public string Name { get; set; }
    /// <summary>
    /// 语音的简称
    /// </summary>
    public string ShortName { get; set; }
    /// <summary>
    /// 语音的性别
    /// </summary>
    public string Gender { get; set; }
    /// <summary>
    /// 语音的区域设置
    /// </summary>
    public string Locale { get; set; }
    /// <summary>
    /// 建议使用的编解码器
    /// </summary>
    public string SuggestedCodec { get; set; }
    /// <summary>
    /// 语音的友好名称
    /// </summary>
    public string FriendlyName { get; set; }
    /// <summary>
    /// 语音的状态
    /// </summary>
    public string Status { get; set; }
    /// <summary>
    /// 语音标签，包含内容类别和语音个性
    /// </summary>
    public Voicetag VoiceTag { get; set; }
}

/// <summary>
/// 语音标签类，包含语音的内容类别和个性特征
/// </summary>
public class Voicetag
{
    /// <summary>
    /// 内容类别数组
    /// </summary>
    public string[] ContentCategories { get; set; }
    /// <summary>
    /// 语音个性特征数组
    /// </summary>
    public string[] VoicePersonalities { get; set; }
}
